version: "3"
services:
  app:
    container_name: theapp_workspace
    build:
      context: ./
      dockerfile: ./docker-conf/PHPAPACHE.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
  mysql:
    build:
      context: ./
      dockerfile: ./docker-conf/MySQL.Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: theapp
      MYSQL_PASSWORD: theapp
      MYSQL_DATABASE: theapp
      MYSQL_ROOT_PASSWORD: theapp
      MYSQL_HOST: localhost
    restart: always
