#!/usr/bin/env bash

isRunning=false

start() {
  docker-compose up -d --force-recreate
  isRunning=true
}

stop() {
  echo "Removing containers"
  docker-compose down --remove-orphans
  isRunning=false
}

restart() {
  stop
  start
}

ssh() {
  if [[ "$isRunning" == false ]]; then
    start
  fi

  echo "Connecting to workspace"

  docker exec -it theapp_workspace bash
}

if [[ -n "$1" ]]; then
  command="$1"
  if [[ -n "$(type -t "${command}")" ]] && [[ "$(type -t "${command}")" == function ]]; then
    "$command" "${@:2}"
    exit
  else
    echo "Command not found"
    exit
  fi
fi